from __future__ import annotations

import os
import re
from pathlib import Path

from .engine import tokens_from_source


def default_bundle_path(report: dict[str, object], suffix: str = "source_bundle") -> Path:
    selected = report["selected"]
    name = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(selected["name"]))
    return Path(f"{name}_{suffix}.c")


def render_c_bundle(report: dict[str, object]) -> str:
    selected = report["selected"]
    deps = report["dependencies"]
    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Generated by src/cpp_meta_query.py source")
    lines.append(f" * Function: {selected['name']}")
    lines.append(
        f" * Location: {selected['file']}:{selected['start_line']}-{selected['end_line']}"
    )
    lines.append(" *")
    lines.append(" * This file is a source-analysis bundle. It is intended for review,")
    lines.append(" * not as a directly compilable C/C++ translation unit.")
    lines.append(" * Nested struct/union/enum/typedef dependencies are included recursively.")
    lines.append(" */")
    lines.append("")
    append_bundle_group(lines, "Constants and macros", deps["constants"])
    append_bundle_group(lines, "Typedefs", deps["typedefs"])
    append_bundle_group(lines, "Enums and enumerators", deps["enums"])
    append_bundle_group(lines, "Global variables", deps["global_variables"])
    append_bundle_group(lines, "Static variables", deps["static_variables"])
    append_bundle_group(lines, "Structures and unions", deps["structures"])
    lines.append("/* ===== Target function source ===== */")
    lines.append(f"/* {selected['file']}:{selected['start_line']}-{selected['end_line']} */")
    lines.append(str(report["source"]).rstrip())
    lines.append("")
    return "\n".join(lines)


def render_subfunction_c_bundle(report: dict[str, object]) -> str:
    selected = report["selected"]
    deps = report["dependencies"]
    functions = report["functions"]
    limits = report["limits"]
    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Generated by src/cpp_meta_query.py subsource")
    lines.append(f" * Root function: {selected['name']}")
    lines.append(
        f" * Location: {selected['file']}:{selected['start_line']}-{selected['end_line']}"
    )
    lines.append(f" * Function bodies included: {len(functions)}")
    lines.append(f" * Auxiliary callees skipped: {len(report.get('skipped_auxiliary_calls', []))}")
    lines.append(
        " * Limits: "
        f"max_depth={limits['max_depth']}, "
        f"max_functions={limits['max_functions']}, "
        f"max_nesting_depth={limits['max_nesting_depth']}, "
        f"include_auxiliary={limits['include_auxiliary']}, "
        f"exclude_test_symbols={limits.get('exclude_test_symbols', False)}"
    )
    lines.append(" *")
    lines.append(" * This file is a source-analysis bundle for knowledge-base construction.")
    lines.append(" * It is intended for review and harness generation, not direct compilation.")
    lines.append(" * Dependency snippets are grouped before function bodies.")
    lines.append(" * Function bodies are ordered with callees before callers when resolvable.")
    lines.append(" * Duplicate definitions are emitted once by symbol kind and name.")
    lines.append(" */")
    lines.append("")
    seen_definitions: set[tuple[str, str]] = set()
    append_bundle_group(lines, "Constants and macros", deps["constants"], seen_definitions)
    append_bundle_group(lines, "Typedefs", deps["typedefs"], seen_definitions)
    append_bundle_group(lines, "Enums and enumerators", deps["enums"], seen_definitions)
    append_bundle_group(lines, "Global variables", deps["global_variables"], seen_definitions)
    append_bundle_group(lines, "Static variables", deps["static_variables"], seen_definitions)
    append_bundle_group(lines, "Structures and unions", deps["structures"], seen_definitions)
    append_skipped_auxiliary_group(lines, report.get("skipped_auxiliary_calls", []))
    lines.append("/* ===== Function sources: callees before callers ===== */")
    if not functions:
        lines.append("/* not found */")
        lines.append("")
        return "\n".join(lines)
    seen_function_names: set[str] = set()
    function_index = 0
    for function_report in functions:
        item = function_report["item"]
        function_name = str(item.get("name", ""))
        if function_name in seen_function_names:
            continue
        seen_function_names.add(function_name)
        function_index += 1
        lines.append(
            f"/* [{function_index}] {item['name']} - {item['file']}:{item['start_line']}-{item['end_line']} */"
        )
        lines.append(str(function_report["source"]).rstrip())
        lines.append("")
    return "\n".join(lines)


def append_skipped_auxiliary_group(lines: list[str], items: object) -> None:
    skipped = items if isinstance(items, list) else []
    lines.append("/* ===== Skipped auxiliary callees ===== */")
    if not skipped:
        lines.append("/* none */")
        lines.append("")
        return
    for item in skipped[:200]:
        callee = item.get("callee", {}) if isinstance(item, dict) else {}
        caller = item.get("caller", {}) if isinstance(item, dict) else {}
        lines.append(
            "/* "
            f"{item.get('name', '<unknown>')} "
            f"called by {caller.get('name', '<unknown>')}:{item.get('line', '?')} "
            f"- {callee.get('file', '<unknown>')}:{callee.get('start_line', '?')}"
            " */"
        )
    if len(skipped) > 200:
        lines.append(f"/* ... {len(skipped) - 200} more skipped auxiliary callees */")
    lines.append("")


def sort_bundle_items_by_references(items: list[dict[str, object]]) -> list[dict[str, object]]:
    by_name: dict[str, dict[str, object]] = {}
    for item in items:
        name = str(item.get("name", ""))
        if name and name not in by_name:
            by_name[name] = item

    ordered: list[dict[str, object]] = []
    permanent: set[str] = set()
    temporary: set[str] = set()

    def visit(name: str) -> None:
        if name in permanent:
            return
        if name in temporary:
            return
        item = by_name.get(name)
        if item is None:
            return
        temporary.add(name)
        snippet = str(item.get("snippet", ""))
        refs = sorted(token for token in tokens_from_source(snippet) if token in by_name and token != name)
        for ref in refs:
            visit(ref)
        temporary.remove(name)
        permanent.add(name)
        ordered.append(item)

    for item in items:
        visit(str(item.get("name", "")))
    seen_ids: set[int] = set()
    result: list[dict[str, object]] = []
    for item in ordered:
        item_id = int(item.get("id", -1))
        if item_id in seen_ids:
            continue
        seen_ids.add(item_id)
        result.append(item)
    return result


def append_bundle_group(
    lines: list[str],
    title: str,
    items: list[dict[str, object]],
    seen_definitions: set[tuple[str, str]] | None = None,
) -> None:
    lines.append(f"/* ===== {title} ===== */")
    if not items:
        lines.append("/* not found */")
        lines.append("")
        return
    seen: set[tuple[str, str, int]] = set()
    emitted = False
    for item in sort_bundle_items_by_references(items):
        key = (str(item["file"]), str(item["name"]), int(item["start_line"]))
        if key in seen:
            continue
        seen.add(key)
        definition_key = bundle_definition_key(item)
        if seen_definitions is not None and definition_key in seen_definitions:
            continue
        if seen_definitions is not None:
            seen_definitions.add(definition_key)
        lines.append(
            f"/* {item['kind']} {item['name']} - {item['file']}:{item['start_line']} */"
        )
        snippet = str(item.get("snippet", "")).rstrip()
        if snippet:
            lines.append(snippet)
        else:
            lines.append("/* source snippet unavailable */")
        lines.append("")
        emitted = True
    if not emitted:
        lines.append("/* duplicate definitions omitted */")
        lines.append("")


def bundle_definition_key(item: dict[str, object]) -> tuple[str, str]:
    kind = str(item.get("kind", ""))
    name = str(item.get("name", "")).strip()
    if kind in {"struct", "union", "enum", "enumerator", "typedef", "macro_define", "variable"}:
        if name:
            return (kind, name)
    snippet = re.sub(r"\s+", " ", str(item.get("snippet", ""))).strip()
    if snippet:
        return ("snippet", snippet)
    return (
        kind,
        f"{item.get('file', '')}:{item.get('start_line', '')}:{item.get('end_line', '')}",
    )


def print_call_sequence(report: dict[str, object]) -> None:
    selected = report["selected"]
    print(
        f"Function: {selected['name']} ({relpath(str(selected['file']))}:"
        f"{selected['start_line']}-{selected['end_line']})"
    )
    calls = report["calls"]
    if not calls:
        print("No direct call sites found.")
        return
    for idx, call in enumerate(calls, start=1):
        target = ""
        if call["resolved_file"]:
            target = f" -> {relpath(str(call['resolved_file']))}:{call['resolved_line']}"
        print(f"{idx}. line {call['line']}: {call['expression']}(){target}")


def print_param_constraints(report: dict[str, object]) -> None:
    selected = report["selected"]
    print(
        f"Function: {selected['name']} ({relpath(str(selected['file']))}:"
        f"{selected['start_line']}-{selected['end_line']})"
    )
    params = report["param_constraints"]
    if not params:
        print("No parameters found.")
        return
    for param in params:
        print()
        print(f"Parameter: {param['name']}")
        print(f"Type/format: {param['type']}")
        inferred = param["inferred"]
        if inferred:
            print("Constraints:")
            for text in inferred:
                print(f"- {text}")
        else:
            print("Constraints: no explicit constraint inferred from function context.")
        evidence = param["evidence"]
        if evidence:
            print("Evidence:")
            for line in evidence:
                print(f"- {line}")


def relpath(path_text: str) -> str:
    try:
        return os.path.relpath(path_text)
    except ValueError:
        return path_text


def print_item_group(title: str, items: list[dict[str, object]]) -> None:
    print(f"### {title}")
    if not items:
        print("- 未发现")
        print()
        return
    for item in items:
        print(
            f"- `{item['name']}` ({item['kind']}, {relpath(str(item['file']))}:{item['start_line']})"
        )
        if item.get("snippet_omitted"):
            location = str(item.get("snippet_location", item.get("file", "<unknown>")))
            print(
                f"  - 代码片段较长，已省略内联内容；位置: "
                f"`{relpath(location)}`，约 {item.get('snippet_lines', '?')} 行。"
            )
            continue
        snippet = str(item.get("snippet", "")).strip()
        if snippet:
            print("```c")
            print(snippet)
            print("```")
    print()


def print_upstream_call_chains(chains: object) -> None:
    chain_list = chains if isinstance(chains, list) else []
    if not chain_list:
        print("- 未发现上层调用链")
        print()
        return
    for idx, chain in enumerate(chain_list, start=1):
        sites = chain if isinstance(chain, list) else []
        names = [
            str(site.get("caller", {}).get("name", "<unknown>"))
            for site in sites
            if isinstance(site, dict)
        ]
        if names:
            print(f"{idx}. " + " -> ".join(names))
        details = []
        for site in sites[:-1]:
            if not isinstance(site, dict):
                continue
            caller = site.get("caller", {})
            if not isinstance(caller, dict):
                continue
            details.append(
                f"{caller.get('name', '<unknown>')}@"
                f"{relpath(str(caller.get('file', '<unknown>')))}:{site.get('line', '?')}"
            )
        if details:
            print("   " + " | ".join(details))
    print()


def print_subfunction_summary(report: dict[str, object]) -> None:
    sub_report = report.get("subfunction_bundle")
    if not isinstance(sub_report, dict):
        print("- 未生成下游子函数分析")
        print()
        return
    functions = sub_report.get("functions", [])
    function_items = functions if isinstance(functions, list) else []
    print(f"- 函数源码数量: {len(function_items)}")
    skipped = sub_report.get("skipped_auxiliary_calls", [])
    skipped_items = skipped if isinstance(skipped, list) else []
    print(f"- 跳过辅助调用数量: {len(skipped_items)}")
    limits = sub_report.get("limits", {})
    if isinstance(limits, dict):
        print(
            "- 限制: "
            f"max_depth={limits.get('max_depth')}, "
            f"max_functions={limits.get('max_functions')}, "
            f"max_nesting_depth={limits.get('max_nesting_depth')}, "
            f"include_auxiliary={limits.get('include_auxiliary')}, "
            f"exclude_test_symbols={limits.get('exclude_test_symbols')}"
        )
    if function_items:
        print("- 函数顺序:")
        for idx, function_report in enumerate(function_items, start=1):
            if not isinstance(function_report, dict):
                continue
            item = function_report.get("item", {})
            if not isinstance(item, dict):
                continue
            print(
                f"  {idx}. `{item.get('name', '<unknown>')}` "
                f"({relpath(str(item.get('file', '<unknown>')))}:"
                f"{item.get('start_line', '?')}-{item.get('end_line', '?')})"
            )
    if skipped_items:
        print("- 跳过的辅助调用:")
        for item in skipped_items[:20]:
            if isinstance(item, dict):
                print(f"  - `{item.get('name', '<unknown>')}` at line {item.get('line', '?')}")
        if len(skipped_items) > 20:
            print(f"  - ... 还有 {len(skipped_items) - 20} 项")
    print()


def print_markdown(report: dict[str, object]) -> None:
    selected = report["selected"]
    print(f"# 函数分析: `{selected['name']}`")
    print()
    print(
        f"- 位置: `{relpath(str(selected['file']))}:{selected['start_line']}-{selected['end_line']}`"
    )
    if report["ambiguous_candidates"]:
        print(f"- 还有 {len(report['ambiguous_candidates'])} 个同名候选，当前选择源码跨度最大的定义。")
    print()
    print("## 函数源码")
    if report.get("source_omitted"):
        print(
            "- 函数源码较长，已省略内联内容；位置: "
            f"`{relpath(str(report.get('source_location', selected['file'])))}`，"
            f"约 {report.get('source_lines', '?')} 行。"
        )
    else:
        print("```c")
        print(report["source"])
        print("```")
    print()

    deps = report["dependencies"]
    print("## 源码依赖片段")
    print_item_group("常量/宏", deps["constants"])
    print_item_group("typedef 类型", deps["typedefs"])
    print_item_group("枚举/枚举值", deps["enums"])
    print_item_group("全局变量", deps["global_variables"])
    print_item_group("静态变量", deps["static_variables"])
    print_item_group("结构体/联合体", deps["structures"])

    print("## 上层调用链")
    print_upstream_call_chains(report.get("call_chains", []))

    print("## 下游子函数源码分析")
    print_subfunction_summary(report)

    print("## 目标函数直接调用点")
    calls = report.get("calls", [])
    if not calls:
        print("- 未发现直接调用")
    for idx, call in enumerate(calls, start=1):
        target = ""
        if call["resolved_file"]:
            target = f" -> `{relpath(str(call['resolved_file']))}:{call['resolved_line']}`"
        print(f"{idx}. line {call['line']}: `{call['expression']}()`{target}")
    print()

    print("## 入参约束和格式")
    params = report["param_constraints"]
    if not params:
        print("- 无入参")
    for param in params:
        print(f"### `{param['name']}`")
        print(f"- 类型/格式: `{param['type']}`")
        inferred = param["inferred"]
        if inferred:
            for text in inferred:
                print(f"- {text}")
        else:
            print("- 未从函数上下文发现显式约束。")
        evidence = param["evidence"]
        if evidence:
            print("- 证据:")
            for line in evidence:
                print(f"  - `{line}`")
    print()

    print("## 说明")
    for note in report["notes"]:
        print(f"- {note}")



